export const ALL_POKEMON_LOADING = "ALL_POKEMON_LOADING";
export const ALL_POKEMON_FAIL = "ALL_POKEMON_FAIL";
export const ALL_POKEMON_SUCCESS = "ALL_POKEMON_SUCCESS";

export const POKEMON_LOADING = "POKEMON_LOADING";
export const POKEMON_FAIL = "POKEMON_FAIL";
export const POKEMON_SUCCESS = "POKEMON_SUCCESS";
